Repository proot-me/proot, pull requests merged in 2022-01, with the labels that each got.

#311 Error out when trying to set PTRACE_O_TRACESECCOMP under ptrace emulation.
  src/ptrace/ptrace.c
Labels: area/seccomp

#308 Set the restart_how field in a newly created child tracee.
  src/tracee/event.c
  src/tracee/tracee.c
Labels: area/ptrace-emulation

#309 Remove unnecessary dependency of proot on libarchive.
  src/GNUmakefile
Labels: kind/build-system
